version: "3.7"
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./schemas/abbserver.sql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: